#!/bin/bash

set -x

if [[ ! $1 ]] ; then 
  echo "No version \$1 (e.g. 1.7.0)"
  exit 1
fi

version=$1



# --------------------------------------------------------------------
# Make the archive docs    
# --------------------------------------------------------------------
cd docs

make html $version

# --------------------------------------------------------------------
# Add and commit the archive
# --------------------------------------------------------------------
git add \
    $version/*.html \
    $version/class/*.html \
    $version/function/*.html \
    $version/method/*.html \
    $version/attribute/*.html \
    $version/_downloads/*.nc \
    $version/_sources

git commit -a -m "v$version archive documentation"

# --------------------------------------------------------------------
# Push
# --------------------------------------------------------------------
git push origin master

set +x
