#!/bin/bash

# --------------------------------------------------------------------
# Test the code examples found in tutorial.py
#
# Call as:
#
#   $ ./test_tutorial_code
#
# Returns non-zero return code if any tutoiral code did not work
# --------------------------------------------------------------------

set -x
d=$PWD
cd docs/source
python extract_tutorial_code.py tutorial.rst 
ls -l tutorial.py
./reset_test_tutorial
cd test_tutorial
python ../tutorial.py
rc=$?
if [[ $rc != 0 ]]; then
    echo "Runtime failure in tutorial.py"
    exit $rc
fi
cd $d
echo "tutorial code ran successfully"
set +x
