#!/bin/bash

# --------------------------------------------------------------------
# Install and run tests in ~/tmp
#
# Usage:
#
# $ ./test_release 1.9.0.1
# --------------------------------------------------------------------

set -x

if [[ ! $1 ]] ; then 
  echo "Must set version as \$1 (e.g. 1.9.0.1)"
  exit 1
fi

vn=$1

dir=~/tmp/test_cfdm
rm -fr $dir

pip install dist/cfdm-$vn.tar.gz -t $dir --no-deps

export PYTHONPATH=$dir:$PYTHONPATH
export PATH=$dir/bin:$PATH

cd $dir/cfdm/test

python run_tests.py
test_result_status=$?

set -x

exit $test_result_status
