#!/bin/bash

# --------------------------------------------------------------------
# Run this within a local respository directory to upload the latest
# release to PyPi
#
# It is presumed that `python setup.py sdist` has already been run.
#
#>> ./upload_to_pypi 1.7




# --------------------------------------------------------------------

set -x

if [[ ! $1 ]] ; then
  echo "No version \$1 (e.g. 2.0.1)"
  exit 1
fi

version=$1

tarball=dist/cfdm-${version}.tar.gz

if [[ ! -f $tarball ]] ; then
  echo "Tar ball for cfdm version $version does not exist: $tarball"
  exit 2
fi

twine upload $tarball

set +x
