#!/bin/bash

# ------------------------------------------------------
# Produce a coverage report of the test suite
# ------------------------------------------------------
echo "coverage docs: https://coverage.readthedocs.io"
set -x

option=''
if [[ ! $1 ]] ; then 
    file=run_tests.py
elif [[ ! $2 ]] ; then 
    if [[ $1 == --* ]] ; then
	option=$1
	file=run_tests.py
    else
	file=$1
    fi
else
    option=$1
    file=$2
fi

coverage erase
coverage run --source=.. --omit="*/test/*" $option $file
coverage report
coverage html --title "cfdm test suite coverage report" -d cfdm_coverage_report
set +x
echo "coverage docs: https://coverage.readthedocs.io"
echo "coverage report URL: file://$PWD/cfdm_coverage_report/index.html"
