#!/bin/bash

# --------------------------------------------------------------------
# Run the full test suite and produce a coverage report.
#
# $ run_test_and_coverage
#
# Or to omit the generation of an html report:
#
# $ run_test_and_coverage --nohtml
# --------------------------------------------------------------------
#set -x

if [[ $1 == "--nohtml" ]] ; then 
    generate_html="false"
else
    generate_html="true"
fi

if ! command -v coverage &> /dev/null
then
    echo "Requires the coverage module: install it e.g. via 'pip install coverage'"
    exit 3
fi

coverage erase
coverage run --source=.. --omit="*/test/*" test_Field.py # run_tests.py
# Capture exit status from unit tests
rc=$?

coverage report

if [[ $generate_html == "true" ]] ; then
    mkdir -p cfdm_coverage_report
    coverage html --title "cfdm test suite coverage report" -d cfdm_coverage_report
    
    echo "coverage docs: https://coverage.readthedocs.io"
    echo "coverage report URL: file://$PWD/cfdm_coverage_report/index.html"
fi

# Return exit status from unit tests
exit $rc

#set +x
