#!/bin/bash

set -x

if [[ ! $1 ]] ; then 
  echo "No version \$1 (e.g. 1.7.0)"
  exit 1
fi

version=$1

echo "Update $PWD/source/releases.rst to include version $version ... done? [yes|no]"
read ok

if [[ $ok != 'yes' ]] ; then
  # ------------------------------------------------------------------
  # Quit nicely
  # ------------------------------------------------------------------
  echo "$PWD/source/releases.rst not updated, so not archiving documentation."
  exit 0
fi

# --------------------------------------------------------------------
# Make the archive docs    
# --------------------------------------------------------------------
make html $version

# --------------------------------------------------------------------
# Add, commit and push
# --------------------------------------------------------------------
cd $version
git add _downloads/*.nc *.html */*.html _sources
git commit -a -m "archive v$version documentation"
git push origin master

set +x
